/*
 * Copyright (c) 2017 Team 26, CMPUT 301, University of Alberta - All Rights Reserved.
 * You may use, distribute, or modify this code under terms and conditions of the Code of Student Behavior at University of Alberta.
 * You can find a copy of the license in this project. Otherwise please contact rohan@ualberta.ca
 */

package cmput301f17t26.smores.utils;

import android.widget.ImageView;

import cmput301f17t26.smores.R;
import cmput301f17t26.smores.all_adapters.HabitAdapter;
import cmput301f17t26.smores.all_adapters.SocialAdapter;

/**
 * Created by apate on 2017-11-30.
 */

public class ProgressBarUtil {
    public static void DrawBar(int progress, HabitAdapter.ViewHolder holder, ImageView mProgress) {
        switch (progress) {
            case 0:
                holder.mProgress.setImageResource(R.drawable.bar000); break;
            case 1:
                holder.mProgress.setImageResource(R.drawable.bar001); break;
            case 2:
                holder.mProgress.setImageResource(R.drawable.bar002); break;
            case 3:
                holder.mProgress.setImageResource(R.drawable.bar003); break;
            case 4:
                holder.mProgress.setImageResource(R.drawable.bar004); break;
            case 5:
                holder.mProgress.setImageResource(R.drawable.bar005); break;
            case 6:
                holder.mProgress.setImageResource(R.drawable.bar006); break;
            case 7:
                holder.mProgress.setImageResource(R.drawable.bar007); break;
            case 8:
                holder.mProgress.setImageResource(R.drawable.bar008); break;
            case 9:
                holder.mProgress.setImageResource(R.drawable.bar009); break;
            case 10:
                holder.mProgress.setImageResource(R.drawable.bar010); break;
            case 11:
                holder.mProgress.setImageResource(R.drawable.bar011); break;
            case 12:
                holder.mProgress.setImageResource(R.drawable.bar012); break;
            case 13:
                holder.mProgress.setImageResource(R.drawable.bar013); break;
            case 14:
                holder.mProgress.setImageResource(R.drawable.bar014); break;
            case 15:
                holder.mProgress.setImageResource(R.drawable.bar015); break;
            case 16:
                holder.mProgress.setImageResource(R.drawable.bar016); break;
            case 17:
                holder.mProgress.setImageResource(R.drawable.bar017); break;
            case 18:
                holder.mProgress.setImageResource(R.drawable.bar018); break;
            case 19:
                holder.mProgress.setImageResource(R.drawable.bar019); break;
            case 20:
                holder.mProgress.setImageResource(R.drawable.bar020); break;
            case 21:
                holder.mProgress.setImageResource(R.drawable.bar021); break;
            case 22:
                holder.mProgress.setImageResource(R.drawable.bar022); break;
            case 23:
                holder.mProgress.setImageResource(R.drawable.bar023); break;
            case 24:
                holder.mProgress.setImageResource(R.drawable.bar024); break;
            case 25:
                holder.mProgress.setImageResource(R.drawable.bar025); break;
            case 26:
                holder.mProgress.setImageResource(R.drawable.bar026); break;
            case 27:
                holder.mProgress.setImageResource(R.drawable.bar027); break;
            case 28:
                holder.mProgress.setImageResource(R.drawable.bar028); break;
            case 29:
                holder.mProgress.setImageResource(R.drawable.bar029); break;
            case 30:
                holder.mProgress.setImageResource(R.drawable.bar030); break;
            case 31:
                holder.mProgress.setImageResource(R.drawable.bar031); break;
            case 32:
                holder.mProgress.setImageResource(R.drawable.bar032); break;
            case 33:
                holder.mProgress.setImageResource(R.drawable.bar033); break;
            case 34:
                holder.mProgress.setImageResource(R.drawable.bar034); break;
            case 35:
                holder.mProgress.setImageResource(R.drawable.bar035); break;
            case 36:
                holder.mProgress.setImageResource(R.drawable.bar036); break;
            case 37:
                holder.mProgress.setImageResource(R.drawable.bar037); break;
            case 38:
                holder.mProgress.setImageResource(R.drawable.bar038); break;
            case 39:
                holder.mProgress.setImageResource(R.drawable.bar039); break;
            case 40:
                holder.mProgress.setImageResource(R.drawable.bar040); break;
            case 41:
                holder.mProgress.setImageResource(R.drawable.bar041); break;
            case 42:
                holder.mProgress.setImageResource(R.drawable.bar042); break;
            case 43:
                holder.mProgress.setImageResource(R.drawable.bar043); break;
            case 44:
                holder.mProgress.setImageResource(R.drawable.bar044); break;
            case 45:
                holder.mProgress.setImageResource(R.drawable.bar045); break;
            case 46:
                holder.mProgress.setImageResource(R.drawable.bar046); break;
            case 47:
                holder.mProgress.setImageResource(R.drawable.bar047); break;
            case 48:
                holder.mProgress.setImageResource(R.drawable.bar048); break;
            case 49:
                holder.mProgress.setImageResource(R.drawable.bar049); break;
            case 50:
                holder.mProgress.setImageResource(R.drawable.bar050); break;
            case 51:
                holder.mProgress.setImageResource(R.drawable.bar051); break;
            case 52:
                holder.mProgress.setImageResource(R.drawable.bar052); break;
            case 53:
                holder.mProgress.setImageResource(R.drawable.bar053); break;
            case 54:
                holder.mProgress.setImageResource(R.drawable.bar054); break;
            case 55:
                holder.mProgress.setImageResource(R.drawable.bar055); break;
            case 56:
                holder.mProgress.setImageResource(R.drawable.bar056); break;
            case 57:
                holder.mProgress.setImageResource(R.drawable.bar057); break;
            case 58:
                holder.mProgress.setImageResource(R.drawable.bar058); break;
            case 59:
                holder.mProgress.setImageResource(R.drawable.bar059); break;
            case 60:
                holder.mProgress.setImageResource(R.drawable.bar060); break;
            case 61:
                holder.mProgress.setImageResource(R.drawable.bar061); break;
            case 62:
                holder.mProgress.setImageResource(R.drawable.bar062); break;
            case 63:
                holder.mProgress.setImageResource(R.drawable.bar063); break;
            case 64:
                holder.mProgress.setImageResource(R.drawable.bar064); break;
            case 65:
                holder.mProgress.setImageResource(R.drawable.bar065); break;
            case 66:
                holder.mProgress.setImageResource(R.drawable.bar066); break;
            case 67:
                holder.mProgress.setImageResource(R.drawable.bar067); break;
            case 68:
                holder.mProgress.setImageResource(R.drawable.bar068); break;
            case 69:
                holder.mProgress.setImageResource(R.drawable.bar069); break;
            case 70:
                holder.mProgress.setImageResource(R.drawable.bar070); break;
            case 71:
                holder.mProgress.setImageResource(R.drawable.bar071); break;
            case 72:
                holder.mProgress.setImageResource(R.drawable.bar072); break;
            case 73:
                holder.mProgress.setImageResource(R.drawable.bar073); break;
            case 74:
                holder.mProgress.setImageResource(R.drawable.bar074); break;
            case 75:
                holder.mProgress.setImageResource(R.drawable.bar075); break;
            case 76:
                holder.mProgress.setImageResource(R.drawable.bar076); break;
            case 77:
                holder.mProgress.setImageResource(R.drawable.bar077); break;
            case 78:
                holder.mProgress.setImageResource(R.drawable.bar078); break;
            case 79:
                holder.mProgress.setImageResource(R.drawable.bar079); break;
            case 80:
                holder.mProgress.setImageResource(R.drawable.bar080); break;
            case 81:
                holder.mProgress.setImageResource(R.drawable.bar081); break;
            case 82:
                holder.mProgress.setImageResource(R.drawable.bar082); break;
            case 83:
                holder.mProgress.setImageResource(R.drawable.bar083); break;
            case 84:
                holder.mProgress.setImageResource(R.drawable.bar084); break;
            case 85:
                holder.mProgress.setImageResource(R.drawable.bar085); break;
            case 86:
                holder.mProgress.setImageResource(R.drawable.bar086); break;
            case 87:
                holder.mProgress.setImageResource(R.drawable.bar087); break;
            case 88:
                holder.mProgress.setImageResource(R.drawable.bar088); break;
            case 89:
                holder.mProgress.setImageResource(R.drawable.bar089); break;
            case 90:
                holder.mProgress.setImageResource(R.drawable.bar090); break;
            case 91:
                holder.mProgress.setImageResource(R.drawable.bar091); break;
            case 92:
                holder.mProgress.setImageResource(R.drawable.bar092); break;
            case 93:
                holder.mProgress.setImageResource(R.drawable.bar093); break;
            case 94:
                holder.mProgress.setImageResource(R.drawable.bar094); break;
            case 95:
                holder.mProgress.setImageResource(R.drawable.bar095); break;
            case 96:
                holder.mProgress.setImageResource(R.drawable.bar096); break;
            case 97:
                holder.mProgress.setImageResource(R.drawable.bar097); break;
            case 98:
                holder.mProgress.setImageResource(R.drawable.bar098); break;
            case 99:
                holder.mProgress.setImageResource(R.drawable.bar099); break;
            case 100:
                holder.mProgress.setImageResource(R.drawable.bar100); break;
            default:
                holder.mProgress.setImageResource(R.drawable.errorbar); break;
        }
    }

    public static void DrawBar(int progress, SocialAdapter.ViewHolder holder, ImageView mProgress) {
        switch (progress) {
            case 0:
                holder.mProgress.setImageResource(R.drawable.bar000); break;
            case 1:
                holder.mProgress.setImageResource(R.drawable.bar001); break;
            case 2:
                holder.mProgress.setImageResource(R.drawable.bar002); break;
            case 3:
                holder.mProgress.setImageResource(R.drawable.bar003); break;
            case 4:
                holder.mProgress.setImageResource(R.drawable.bar004); break;
            case 5:
                holder.mProgress.setImageResource(R.drawable.bar005); break;
            case 6:
                holder.mProgress.setImageResource(R.drawable.bar006); break;
            case 7:
                holder.mProgress.setImageResource(R.drawable.bar007); break;
            case 8:
                holder.mProgress.setImageResource(R.drawable.bar008); break;
            case 9:
                holder.mProgress.setImageResource(R.drawable.bar009); break;
            case 10:
                holder.mProgress.setImageResource(R.drawable.bar010); break;
            case 11:
                holder.mProgress.setImageResource(R.drawable.bar011); break;
            case 12:
                holder.mProgress.setImageResource(R.drawable.bar012); break;
            case 13:
                holder.mProgress.setImageResource(R.drawable.bar013); break;
            case 14:
                holder.mProgress.setImageResource(R.drawable.bar014); break;
            case 15:
                holder.mProgress.setImageResource(R.drawable.bar015); break;
            case 16:
                holder.mProgress.setImageResource(R.drawable.bar016); break;
            case 17:
                holder.mProgress.setImageResource(R.drawable.bar017); break;
            case 18:
                holder.mProgress.setImageResource(R.drawable.bar018); break;
            case 19:
                holder.mProgress.setImageResource(R.drawable.bar019); break;
            case 20:
                holder.mProgress.setImageResource(R.drawable.bar020); break;
            case 21:
                holder.mProgress.setImageResource(R.drawable.bar021); break;
            case 22:
                holder.mProgress.setImageResource(R.drawable.bar022); break;
            case 23:
                holder.mProgress.setImageResource(R.drawable.bar023); break;
            case 24:
                holder.mProgress.setImageResource(R.drawable.bar024); break;
            case 25:
                holder.mProgress.setImageResource(R.drawable.bar025); break;
            case 26:
                holder.mProgress.setImageResource(R.drawable.bar026); break;
            case 27:
                holder.mProgress.setImageResource(R.drawable.bar027); break;
            case 28:
                holder.mProgress.setImageResource(R.drawable.bar028); break;
            case 29:
                holder.mProgress.setImageResource(R.drawable.bar029); break;
            case 30:
                holder.mProgress.setImageResource(R.drawable.bar030); break;
            case 31:
                holder.mProgress.setImageResource(R.drawable.bar031); break;
            case 32:
                holder.mProgress.setImageResource(R.drawable.bar032); break;
            case 33:
                holder.mProgress.setImageResource(R.drawable.bar033); break;
            case 34:
                holder.mProgress.setImageResource(R.drawable.bar034); break;
            case 35:
                holder.mProgress.setImageResource(R.drawable.bar035); break;
            case 36:
                holder.mProgress.setImageResource(R.drawable.bar036); break;
            case 37:
                holder.mProgress.setImageResource(R.drawable.bar037); break;
            case 38:
                holder.mProgress.setImageResource(R.drawable.bar038); break;
            case 39:
                holder.mProgress.setImageResource(R.drawable.bar039); break;
            case 40:
                holder.mProgress.setImageResource(R.drawable.bar040); break;
            case 41:
                holder.mProgress.setImageResource(R.drawable.bar041); break;
            case 42:
                holder.mProgress.setImageResource(R.drawable.bar042); break;
            case 43:
                holder.mProgress.setImageResource(R.drawable.bar043); break;
            case 44:
                holder.mProgress.setImageResource(R.drawable.bar044); break;
            case 45:
                holder.mProgress.setImageResource(R.drawable.bar045); break;
            case 46:
                holder.mProgress.setImageResource(R.drawable.bar046); break;
            case 47:
                holder.mProgress.setImageResource(R.drawable.bar047); break;
            case 48:
                holder.mProgress.setImageResource(R.drawable.bar048); break;
            case 49:
                holder.mProgress.setImageResource(R.drawable.bar049); break;
            case 50:
                holder.mProgress.setImageResource(R.drawable.bar050); break;
            case 51:
                holder.mProgress.setImageResource(R.drawable.bar051); break;
            case 52:
                holder.mProgress.setImageResource(R.drawable.bar052); break;
            case 53:
                holder.mProgress.setImageResource(R.drawable.bar053); break;
            case 54:
                holder.mProgress.setImageResource(R.drawable.bar054); break;
            case 55:
                holder.mProgress.setImageResource(R.drawable.bar055); break;
            case 56:
                holder.mProgress.setImageResource(R.drawable.bar056); break;
            case 57:
                holder.mProgress.setImageResource(R.drawable.bar057); break;
            case 58:
                holder.mProgress.setImageResource(R.drawable.bar058); break;
            case 59:
                holder.mProgress.setImageResource(R.drawable.bar059); break;
            case 60:
                holder.mProgress.setImageResource(R.drawable.bar060); break;
            case 61:
                holder.mProgress.setImageResource(R.drawable.bar061); break;
            case 62:
                holder.mProgress.setImageResource(R.drawable.bar062); break;
            case 63:
                holder.mProgress.setImageResource(R.drawable.bar063); break;
            case 64:
                holder.mProgress.setImageResource(R.drawable.bar064); break;
            case 65:
                holder.mProgress.setImageResource(R.drawable.bar065); break;
            case 66:
                holder.mProgress.setImageResource(R.drawable.bar066); break;
            case 67:
                holder.mProgress.setImageResource(R.drawable.bar067); break;
            case 68:
                holder.mProgress.setImageResource(R.drawable.bar068); break;
            case 69:
                holder.mProgress.setImageResource(R.drawable.bar069); break;
            case 70:
                holder.mProgress.setImageResource(R.drawable.bar070); break;
            case 71:
                holder.mProgress.setImageResource(R.drawable.bar071); break;
            case 72:
                holder.mProgress.setImageResource(R.drawable.bar072); break;
            case 73:
                holder.mProgress.setImageResource(R.drawable.bar073); break;
            case 74:
                holder.mProgress.setImageResource(R.drawable.bar074); break;
            case 75:
                holder.mProgress.setImageResource(R.drawable.bar075); break;
            case 76:
                holder.mProgress.setImageResource(R.drawable.bar076); break;
            case 77:
                holder.mProgress.setImageResource(R.drawable.bar077); break;
            case 78:
                holder.mProgress.setImageResource(R.drawable.bar078); break;
            case 79:
                holder.mProgress.setImageResource(R.drawable.bar079); break;
            case 80:
                holder.mProgress.setImageResource(R.drawable.bar080); break;
            case 81:
                holder.mProgress.setImageResource(R.drawable.bar081); break;
            case 82:
                holder.mProgress.setImageResource(R.drawable.bar082); break;
            case 83:
                holder.mProgress.setImageResource(R.drawable.bar083); break;
            case 84:
                holder.mProgress.setImageResource(R.drawable.bar084); break;
            case 85:
                holder.mProgress.setImageResource(R.drawable.bar085); break;
            case 86:
                holder.mProgress.setImageResource(R.drawable.bar086); break;
            case 87:
                holder.mProgress.setImageResource(R.drawable.bar087); break;
            case 88:
                holder.mProgress.setImageResource(R.drawable.bar088); break;
            case 89:
                holder.mProgress.setImageResource(R.drawable.bar089); break;
            case 90:
                holder.mProgress.setImageResource(R.drawable.bar090); break;
            case 91:
                holder.mProgress.setImageResource(R.drawable.bar091); break;
            case 92:
                holder.mProgress.setImageResource(R.drawable.bar092); break;
            case 93:
                holder.mProgress.setImageResource(R.drawable.bar093); break;
            case 94:
                holder.mProgress.setImageResource(R.drawable.bar094); break;
            case 95:
                holder.mProgress.setImageResource(R.drawable.bar095); break;
            case 96:
                holder.mProgress.setImageResource(R.drawable.bar096); break;
            case 97:
                holder.mProgress.setImageResource(R.drawable.bar097); break;
            case 98:
                holder.mProgress.setImageResource(R.drawable.bar098); break;
            case 99:
                holder.mProgress.setImageResource(R.drawable.bar099); break;
            case 100:
                holder.mProgress.setImageResource(R.drawable.bar100); break;
            default:
                holder.mProgress.setImageResource(R.drawable.errorbar); break;
        }
    }

    public static void DrawBar(int progress, ImageView mStats) {
        switch (progress) {
            case 0:
                mStats.setImageResource(R.drawable.stat000); break;
            case 1:
                mStats.setImageResource(R.drawable.stat001); break;
            case 2:
                mStats.setImageResource(R.drawable.stat002); break;
            case 3:
                mStats.setImageResource(R.drawable.stat003); break;
            case 4:
                mStats.setImageResource(R.drawable.stat004); break;
            case 5:
                mStats.setImageResource(R.drawable.stat005); break;
            case 6:
                mStats.setImageResource(R.drawable.stat006); break;
            case 7:
                mStats.setImageResource(R.drawable.stat007); break;
            case 8:
                mStats.setImageResource(R.drawable.stat008); break;
            case 9:
                mStats.setImageResource(R.drawable.stat009); break;
            case 10:
                mStats.setImageResource(R.drawable.stat010); break;
            case 11:
                mStats.setImageResource(R.drawable.stat011); break;
            case 12:
                mStats.setImageResource(R.drawable.stat012); break;
            case 13:
                mStats.setImageResource(R.drawable.stat013); break;
            case 14:
                mStats.setImageResource(R.drawable.stat014); break;
            case 15:
                mStats.setImageResource(R.drawable.stat015); break;
            case 16:
                mStats.setImageResource(R.drawable.stat016); break;
            case 17:
                mStats.setImageResource(R.drawable.stat017); break;
            case 18:
                mStats.setImageResource(R.drawable.stat018); break;
            case 19:
                mStats.setImageResource(R.drawable.stat019); break;
            case 20:
                mStats.setImageResource(R.drawable.stat020); break;
            case 21:
                mStats.setImageResource(R.drawable.stat021); break;
            case 22:
                mStats.setImageResource(R.drawable.stat022); break;
            case 23:
                mStats.setImageResource(R.drawable.stat023); break;
            case 24:
                mStats.setImageResource(R.drawable.stat024); break;
            case 25:
                mStats.setImageResource(R.drawable.stat025); break;
            case 26:
                mStats.setImageResource(R.drawable.stat026); break;
            case 27:
                mStats.setImageResource(R.drawable.stat027); break;
            case 28:
                mStats.setImageResource(R.drawable.stat028); break;
            case 29:
                mStats.setImageResource(R.drawable.stat029); break;
            case 30:
                mStats.setImageResource(R.drawable.stat030); break;
            case 31:
                mStats.setImageResource(R.drawable.stat031); break;
            case 32:
                mStats.setImageResource(R.drawable.stat032); break;
            case 33:
                mStats.setImageResource(R.drawable.stat033); break;
            case 34:
                mStats.setImageResource(R.drawable.stat034); break;
            case 35:
                mStats.setImageResource(R.drawable.stat035); break;
            case 36:
                mStats.setImageResource(R.drawable.stat036); break;
            case 37:
                mStats.setImageResource(R.drawable.stat037); break;
            case 38:
                mStats.setImageResource(R.drawable.stat038); break;
            case 39:
                mStats.setImageResource(R.drawable.stat039); break;
            case 40:
                mStats.setImageResource(R.drawable.stat040); break;
            case 41:
                mStats.setImageResource(R.drawable.stat041); break;
            case 42:
                mStats.setImageResource(R.drawable.stat042); break;
            case 43:
                mStats.setImageResource(R.drawable.stat043); break;
            case 44:
                mStats.setImageResource(R.drawable.stat044); break;
            case 45:
                mStats.setImageResource(R.drawable.stat045); break;
            case 46:
                mStats.setImageResource(R.drawable.stat046); break;
            case 47:
                mStats.setImageResource(R.drawable.stat047); break;
            case 48:
                mStats.setImageResource(R.drawable.stat048); break;
            case 49:
                mStats.setImageResource(R.drawable.stat049); break;
            case 50:
                mStats.setImageResource(R.drawable.stat050); break;
            case 51:
                mStats.setImageResource(R.drawable.stat051); break;
            case 52:
                mStats.setImageResource(R.drawable.stat052); break;
            case 53:
                mStats.setImageResource(R.drawable.stat053); break;
            case 54:
                mStats.setImageResource(R.drawable.stat054); break;
            case 55:
                mStats.setImageResource(R.drawable.stat055); break;
            case 56:
                mStats.setImageResource(R.drawable.stat056); break;
            case 57:
                mStats.setImageResource(R.drawable.stat057); break;
            case 58:
                mStats.setImageResource(R.drawable.stat058); break;
            case 59:
                mStats.setImageResource(R.drawable.stat059); break;
            case 60:
                mStats.setImageResource(R.drawable.stat060); break;
            case 61:
                mStats.setImageResource(R.drawable.stat061); break;
            case 62:
                mStats.setImageResource(R.drawable.stat062); break;
            case 63:
                mStats.setImageResource(R.drawable.stat063); break;
            case 64:
                mStats.setImageResource(R.drawable.stat064); break;
            case 65:
                mStats.setImageResource(R.drawable.stat065); break;
            case 66:
                mStats.setImageResource(R.drawable.stat066); break;
            case 67:
                mStats.setImageResource(R.drawable.stat067); break;
            case 68:
                mStats.setImageResource(R.drawable.stat068); break;
            case 69:
                mStats.setImageResource(R.drawable.stat069); break;
            case 70:
                mStats.setImageResource(R.drawable.stat070); break;
            case 71:
                mStats.setImageResource(R.drawable.stat071); break;
            case 72:
                mStats.setImageResource(R.drawable.stat072); break;
            case 73:
                mStats.setImageResource(R.drawable.stat073); break;
            case 74:
                mStats.setImageResource(R.drawable.stat074); break;
            case 75:
                mStats.setImageResource(R.drawable.stat075); break;
            case 76:
                mStats.setImageResource(R.drawable.stat076); break;
            case 77:
                mStats.setImageResource(R.drawable.stat077); break;
            case 78:
                mStats.setImageResource(R.drawable.stat078); break;
            case 79:
                mStats.setImageResource(R.drawable.stat079); break;
            case 80:
                mStats.setImageResource(R.drawable.stat080); break;
            case 81:
                mStats.setImageResource(R.drawable.stat081); break;
            case 82:
                mStats.setImageResource(R.drawable.stat082); break;
            case 83:
                mStats.setImageResource(R.drawable.stat083); break;
            case 84:
                mStats.setImageResource(R.drawable.stat084); break;
            case 85:
                mStats.setImageResource(R.drawable.stat085); break;
            case 86:
                mStats.setImageResource(R.drawable.stat086); break;
            case 87:
                mStats.setImageResource(R.drawable.stat087); break;
            case 88:
                mStats.setImageResource(R.drawable.stat088); break;
            case 89:
                mStats.setImageResource(R.drawable.stat089); break;
            case 90:
                mStats.setImageResource(R.drawable.stat090); break;
            case 91:
                mStats.setImageResource(R.drawable.stat091); break;
            case 92:
                mStats.setImageResource(R.drawable.stat092); break;
            case 93:
                mStats.setImageResource(R.drawable.stat093); break;
            case 94:
                mStats.setImageResource(R.drawable.stat094); break;
            case 95:
                mStats.setImageResource(R.drawable.stat095); break;
            case 96:
                mStats.setImageResource(R.drawable.stat096); break;
            case 97:
                mStats.setImageResource(R.drawable.stat097); break;
            case 98:
                mStats.setImageResource(R.drawable.stat098); break;
            case 99:
                mStats.setImageResource(R.drawable.stat099); break;
            case 100:
                mStats.setImageResource(R.drawable.stat100); break;
            default:
                mStats.setImageResource(R.drawable.stat000); break;
        }
    }
}
